//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormCases2.Auth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Auth.AuthSoap")]
    public interface AuthSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WebFormCases2.Auth.LoginResponse Login(WebFormCases2.Auth.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormCases2.Auth.LoginResponse> LoginAsync(WebFormCases2.Auth.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name GetMsgResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMsg", ReplyAction="*")]
        WebFormCases2.Auth.GetMsgResponse GetMsg(WebFormCases2.Auth.GetMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormCases2.Auth.GetMsgResponse> GetMsgAsync(WebFormCases2.Auth.GetMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogOut", ReplyAction="*")]
        void LogOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogOut", ReplyAction="*")]
        System.Threading.Tasks.Task LogOutAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WebFormCases2.Auth.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebFormCases2.Auth.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormCases2.Auth.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WebFormCases2.Auth.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMsg", Namespace="http://tempuri.org/", Order=0)]
        public WebFormCases2.Auth.GetMsgRequestBody Body;
        
        public GetMsgRequest() {
        }
        
        public GetMsgRequest(WebFormCases2.Auth.GetMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMsgRequestBody {
        
        public GetMsgRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMsgResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormCases2.Auth.GetMsgResponseBody Body;
        
        public GetMsgResponse() {
        }
        
        public GetMsgResponse(WebFormCases2.Auth.GetMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMsgResult;
        
        public GetMsgResponseBody() {
        }
        
        public GetMsgResponseBody(string GetMsgResult) {
            this.GetMsgResult = GetMsgResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthSoapChannel : WebFormCases2.Auth.AuthSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthSoapClient : System.ServiceModel.ClientBase<WebFormCases2.Auth.AuthSoap>, WebFormCases2.Auth.AuthSoap {
        
        public AuthSoapClient() {
        }
        
        public AuthSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormCases2.Auth.LoginResponse WebFormCases2.Auth.AuthSoap.Login(WebFormCases2.Auth.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string username, string password) {
            WebFormCases2.Auth.LoginRequest inValue = new WebFormCases2.Auth.LoginRequest();
            inValue.Body = new WebFormCases2.Auth.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebFormCases2.Auth.LoginResponse retVal = ((WebFormCases2.Auth.AuthSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormCases2.Auth.LoginResponse> WebFormCases2.Auth.AuthSoap.LoginAsync(WebFormCases2.Auth.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormCases2.Auth.LoginResponse> LoginAsync(string username, string password) {
            WebFormCases2.Auth.LoginRequest inValue = new WebFormCases2.Auth.LoginRequest();
            inValue.Body = new WebFormCases2.Auth.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebFormCases2.Auth.AuthSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormCases2.Auth.GetMsgResponse WebFormCases2.Auth.AuthSoap.GetMsg(WebFormCases2.Auth.GetMsgRequest request) {
            return base.Channel.GetMsg(request);
        }
        
        public string GetMsg() {
            WebFormCases2.Auth.GetMsgRequest inValue = new WebFormCases2.Auth.GetMsgRequest();
            inValue.Body = new WebFormCases2.Auth.GetMsgRequestBody();
            WebFormCases2.Auth.GetMsgResponse retVal = ((WebFormCases2.Auth.AuthSoap)(this)).GetMsg(inValue);
            return retVal.Body.GetMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormCases2.Auth.GetMsgResponse> WebFormCases2.Auth.AuthSoap.GetMsgAsync(WebFormCases2.Auth.GetMsgRequest request) {
            return base.Channel.GetMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormCases2.Auth.GetMsgResponse> GetMsgAsync() {
            WebFormCases2.Auth.GetMsgRequest inValue = new WebFormCases2.Auth.GetMsgRequest();
            inValue.Body = new WebFormCases2.Auth.GetMsgRequestBody();
            return ((WebFormCases2.Auth.AuthSoap)(this)).GetMsgAsync(inValue);
        }
        
        public void LogOut() {
            base.Channel.LogOut();
        }
        
        public System.Threading.Tasks.Task LogOutAsync() {
            return base.Channel.LogOutAsync();
        }
    }
}
